server:
  port: 8001    #???
spring:
  application:
    name: eureka-server # ???????Eureka??????id???serviceId?
eureka:
  client:
    register-with-eureka: false   #????????Eureka?
    fetch-registry: false   #???eureka???????
    service-url:
      defaultZone: http://localhost:8001/eureka